-- =====================================================================
-- Suwayomi-next schema baseline (PostgreSQL)
-- Derived from Suwayomi-Server (commit 4b2c19ab) current Exposed table
-- definitions + net effect of migrations M0001..M0062.
-- All tables live in the `suwayomi` schema (matches M0054).
-- Naming: lowercase table/column names (PostgreSQL convention; H2 stored
-- them case-insensitively / uppercase, Exposed emits lowercase on PG).
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS suwayomi;

CREATE TABLE IF NOT EXISTS suwayomi.extension (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    apk_name        VARCHAR(1024),
    store_index_url VARCHAR(2048),
    icon_url        VARCHAR(2048) NOT NULL DEFAULT 'https://raw.githubusercontent.com/tachiyomiorg/tachiyomi/64ba127e7d43b1d7e6d58a6f5c9b2bd5fe0543f7/app/src/main/res/mipmap-xxxhdpi/ic_local_source.webp',
    name            VARCHAR(128) NOT NULL,
    pkg_name        VARCHAR(128) NOT NULL,
    apk_url         VARCHAR(2048),
    jar_url         VARCHAR(2048),
    extension_lib   VARCHAR(16),
    version_name    VARCHAR(16) NOT NULL,
    version_code    BIGINT NOT NULL,
    lang            VARCHAR(32) NOT NULL,
    content_warning INTEGER NOT NULL,
    is_installed    BOOLEAN NOT NULL DEFAULT FALSE,
    has_update      BOOLEAN NOT NULL DEFAULT FALSE,
    is_obsolete     BOOLEAN NOT NULL DEFAULT FALSE,
    class_name      VARCHAR(1024) NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_extension_pkg_name ON suwayomi.extension (pkg_name);
CREATE INDEX IF NOT EXISTS idx_extension_store_index_url ON suwayomi.extension (store_index_url);

CREATE TABLE IF NOT EXISTS suwayomi.source (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(128) NOT NULL,
    lang            VARCHAR(32) NOT NULL,
    extension       INTEGER NOT NULL,
    content_warning INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS suwayomi.manga (
    id                          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url                         VARCHAR(2048) NOT NULL,
    title                       VARCHAR(512) NOT NULL,
    initialized                 BOOLEAN NOT NULL DEFAULT FALSE,
    artist                      TEXT,
    author                      TEXT,
    description                 TEXT,
    genre                       TEXT,
    status                      INTEGER NOT NULL DEFAULT 0,
    thumbnail_url               VARCHAR(2048),
    thumbnail_url_last_fetched  BIGINT NOT NULL DEFAULT 0,
    in_library                  BOOLEAN NOT NULL DEFAULT FALSE,
    in_library_at               BIGINT NOT NULL DEFAULT 0,
    source                      BIGINT NOT NULL,
    real_url                    VARCHAR(2048),
    last_fetched_at             BIGINT NOT NULL DEFAULT 0,
    chapters_last_fetched_at    BIGINT NOT NULL DEFAULT 0,
    update_strategy             VARCHAR(256) NOT NULL DEFAULT 'ALWAYS_UPDATE',
    last_modified_at            BIGINT NOT NULL DEFAULT 0,
    version                     BIGINT NOT NULL DEFAULT 0,
    is_syncing                  BOOLEAN NOT NULL DEFAULT FALSE,
    memo                        TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS suwayomi.chapter (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url             VARCHAR(2048) NOT NULL,
    name            VARCHAR(512) NOT NULL,
    date_upload     BIGINT NOT NULL DEFAULT 0,
    chapter_number  REAL NOT NULL DEFAULT -1,
    scanlator       VARCHAR(256),
    read            BOOLEAN NOT NULL DEFAULT FALSE,
    bookmark        BOOLEAN NOT NULL DEFAULT FALSE,
    last_page_read  INTEGER NOT NULL DEFAULT 0,
    last_read_at    BIGINT NOT NULL DEFAULT 0,
    fetched_at      BIGINT NOT NULL DEFAULT 0,
    source_order    INTEGER NOT NULL,
    real_url        VARCHAR(2048),
    is_downloaded   BOOLEAN NOT NULL DEFAULT FALSE,
    page_count      INTEGER NOT NULL DEFAULT -1,
    manga           INTEGER NOT NULL,
    koreader_hash   VARCHAR(32),
    last_modified_at BIGINT NOT NULL DEFAULT 0,
    version         BIGINT NOT NULL DEFAULT 0,
    is_syncing      BOOLEAN NOT NULL DEFAULT FALSE,
    memo            TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS suwayomi.page (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index     INTEGER NOT NULL,
    url       VARCHAR(2048) NOT NULL,
    image_url TEXT,
    chapter   INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS suwayomi.category (
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(64) NOT NULL,
    sort_order          INTEGER NOT NULL DEFAULT 0,
    is_default          BOOLEAN NOT NULL DEFAULT FALSE,
    include_in_update   INTEGER NOT NULL DEFAULT -1,
    include_in_download INTEGER NOT NULL DEFAULT -1,
    version             BIGINT NOT NULL DEFAULT 0,
    uid                 BIGINT NOT NULL DEFAULT 0,
    last_modified_at    BIGINT NOT NULL DEFAULT 0,
    is_syncing          BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS suwayomi.category_manga (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category INTEGER NOT NULL,
    manga    INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS suwayomi.category_meta (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meta_key    VARCHAR(256) NOT NULL,
    value       VARCHAR(4096) NOT NULL,
    category_ref INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS suwayomi.chapter_meta (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meta_key    VARCHAR(256) NOT NULL,
    value       VARCHAR(4096) NOT NULL,
    chapter_ref INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS suwayomi.manga_meta (
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meta_key  VARCHAR(256) NOT NULL,
    value     VARCHAR(4096) NOT NULL,
    manga_ref INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS suwayomi.source_meta (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meta_key   VARCHAR(256) NOT NULL,
    value      VARCHAR(4096) NOT NULL,
    source_ref BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS suwayomi.global_meta (
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meta_key VARCHAR(256) NOT NULL,
    value    VARCHAR(4096) NOT NULL
);

CREATE TABLE IF NOT EXISTS suwayomi.extension_store (
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    index_url          VARCHAR(2048) NOT NULL,
    name               VARCHAR(256) NOT NULL,
    badge_label        VARCHAR(32) NOT NULL,
    signing_key        VARCHAR(512) NOT NULL,
    contact_website    VARCHAR(2048) NOT NULL,
    contact_discord    VARCHAR(2048),
    is_legacy          BOOLEAN NOT NULL DEFAULT FALSE,
    extension_list_url VARCHAR(2048)
);

CREATE TABLE IF NOT EXISTS suwayomi.track_record (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manga_id          INTEGER NOT NULL,
    sync_id           INTEGER NOT NULL,
    remote_id         BIGINT NOT NULL,
    library_id        BIGINT,
    title             VARCHAR(512) NOT NULL,
    last_chapter_read DOUBLE PRECISION NOT NULL,
    total_chapters    INTEGER NOT NULL,
    status            INTEGER NOT NULL,
    score             DOUBLE PRECISION NOT NULL,
    remote_url        VARCHAR(512) NOT NULL,
    start_date        BIGINT NOT NULL,
    finish_date       BIGINT NOT NULL,
    private           BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS suwayomi.track_search (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracker_id            INTEGER NOT NULL,
    remote_id             BIGINT NOT NULL,
    title                 VARCHAR(512) NOT NULL,
    total_chapters        INTEGER NOT NULL,
    tracking_url          VARCHAR(512) NOT NULL,
    cover_url             VARCHAR(512) NOT NULL,
    summary               VARCHAR(4096) NOT NULL,
    publishing_status     VARCHAR(512) NOT NULL,
    publishing_type       VARCHAR(512) NOT NULL,
    start_date            VARCHAR(128) NOT NULL,
    library_id            BIGINT DEFAULT NULL,
    last_chapter_read     DOUBLE PRECISION NOT NULL DEFAULT 0,
    status                INTEGER NOT NULL DEFAULT 0,
    score                 DOUBLE PRECISION NOT NULL DEFAULT 0,
    started_reading_date  BIGINT NOT NULL DEFAULT 0,
    finished_reading_date BIGINT NOT NULL DEFAULT 0,
    private               BOOLEAN NOT NULL DEFAULT FALSE,
    authors               VARCHAR(256) DEFAULT NULL,
    artists               VARCHAR(256) DEFAULT NULL
);

-- foreign keys (CASCADE per M0028 / M0033; unique constraints per M0040/M0049/M0060/M0062)
ALTER TABLE suwayomi.source DROP CONSTRAINT IF EXISTS fk_source_extension;
ALTER TABLE suwayomi.source ADD CONSTRAINT fk_source_extension FOREIGN KEY (extension) REFERENCES suwayomi.extension (id);
ALTER TABLE suwayomi.chapter DROP CONSTRAINT IF EXISTS fk_chapter_manga;
ALTER TABLE suwayomi.chapter ADD CONSTRAINT fk_chapter_manga FOREIGN KEY (manga) REFERENCES suwayomi.manga (id) ON DELETE CASCADE;
ALTER TABLE suwayomi.page DROP CONSTRAINT IF EXISTS fk_page_chapter;
ALTER TABLE suwayomi.page ADD CONSTRAINT fk_page_chapter FOREIGN KEY (chapter) REFERENCES suwayomi.chapter (id) ON DELETE CASCADE;
ALTER TABLE suwayomi.category_manga DROP CONSTRAINT IF EXISTS fk_category_manga_category;
ALTER TABLE suwayomi.category_manga ADD CONSTRAINT fk_category_manga_category FOREIGN KEY (category) REFERENCES suwayomi.category (id) ON DELETE CASCADE;
ALTER TABLE suwayomi.category_manga DROP CONSTRAINT IF EXISTS fk_category_manga_manga;
ALTER TABLE suwayomi.category_manga ADD CONSTRAINT fk_category_manga_manga FOREIGN KEY (manga) REFERENCES suwayomi.manga (id) ON DELETE CASCADE;
ALTER TABLE suwayomi.category_meta DROP CONSTRAINT IF EXISTS fk_category_meta_ref;
ALTER TABLE suwayomi.category_meta ADD CONSTRAINT fk_category_meta_ref FOREIGN KEY (category_ref) REFERENCES suwayomi.category (id) ON DELETE CASCADE;
ALTER TABLE suwayomi.chapter_meta DROP CONSTRAINT IF EXISTS fk_chapter_meta_ref;
ALTER TABLE suwayomi.chapter_meta ADD CONSTRAINT fk_chapter_meta_ref FOREIGN KEY (chapter_ref) REFERENCES suwayomi.chapter (id) ON DELETE CASCADE;
ALTER TABLE suwayomi.manga_meta DROP CONSTRAINT IF EXISTS fk_manga_meta_ref;
ALTER TABLE suwayomi.manga_meta ADD CONSTRAINT fk_manga_meta_ref FOREIGN KEY (manga_ref) REFERENCES suwayomi.manga (id) ON DELETE CASCADE;
ALTER TABLE suwayomi.track_record DROP CONSTRAINT IF EXISTS fk_track_record_manga;
ALTER TABLE suwayomi.track_record ADD CONSTRAINT fk_track_record_manga FOREIGN KEY (manga_id) REFERENCES suwayomi.manga (id) ON DELETE CASCADE;

ALTER TABLE suwayomi.chapter DROP CONSTRAINT IF EXISTS uq_chapter;
ALTER TABLE suwayomi.chapter ADD CONSTRAINT uq_chapter UNIQUE (url, manga);
ALTER TABLE suwayomi.category_meta DROP CONSTRAINT IF EXISTS uq_category_meta;
ALTER TABLE suwayomi.category_meta ADD CONSTRAINT uq_category_meta UNIQUE (category_ref, meta_key);
ALTER TABLE suwayomi.chapter_meta DROP CONSTRAINT IF EXISTS uq_chapter_meta;
ALTER TABLE suwayomi.chapter_meta ADD CONSTRAINT uq_chapter_meta UNIQUE (chapter_ref, meta_key);
ALTER TABLE suwayomi.global_meta DROP CONSTRAINT IF EXISTS uq_global_meta;
ALTER TABLE suwayomi.global_meta ADD CONSTRAINT uq_global_meta UNIQUE (meta_key);
ALTER TABLE suwayomi.manga_meta DROP CONSTRAINT IF EXISTS uq_manga_meta;
ALTER TABLE suwayomi.manga_meta ADD CONSTRAINT uq_manga_meta UNIQUE (manga_ref, meta_key);
ALTER TABLE suwayomi.source_meta DROP CONSTRAINT IF EXISTS uq_source_meta;
ALTER TABLE suwayomi.source_meta ADD CONSTRAINT uq_source_meta UNIQUE (source_ref, meta_key);
ALTER TABLE suwayomi.category_manga DROP CONSTRAINT IF EXISTS uq_category_manga;
ALTER TABLE suwayomi.category_manga ADD CONSTRAINT uq_category_manga UNIQUE (manga, category);
ALTER TABLE suwayomi.extension_store DROP CONSTRAINT IF EXISTS uq_extension_store_index_url;
ALTER TABLE suwayomi.extension_store ADD CONSTRAINT uq_extension_store_index_url UNIQUE (index_url);

-- foreign key indexes (M0061)
CREATE INDEX IF NOT EXISTS idx_category_manga_category ON suwayomi.category_manga (category);
CREATE INDEX IF NOT EXISTS idx_category_manga_manga ON suwayomi.category_manga (manga);
CREATE INDEX IF NOT EXISTS idx_category_meta_category ON suwayomi.category_meta (category_ref);
CREATE INDEX IF NOT EXISTS idx_chapter_manga ON suwayomi.chapter (manga);
CREATE INDEX IF NOT EXISTS idx_chapter_meta_chapter ON suwayomi.chapter_meta (chapter_ref);
CREATE INDEX IF NOT EXISTS idx_manga_meta_manga ON suwayomi.manga_meta (manga_ref);
CREATE INDEX IF NOT EXISTS idx_page_chapter ON suwayomi.page (chapter);
CREATE INDEX IF NOT EXISTS idx_source_extension ON suwayomi.source (extension);
CREATE INDEX IF NOT EXISTS idx_source_meta_source ON suwayomi.source_meta (source_ref);
CREATE INDEX IF NOT EXISTS idx_track_record_manga ON suwayomi.track_record (manga_id);

-- TODO(Phase 1): migration state table used by de.neonew.exposed.migrations
-- (verify exact name/columns against a Kotlin-created database, then mirror it
-- so an existing DB's migration history is respected).