-- =====================================================================
-- Suwayomi-next schema baseline (SQLite)
--
-- Translation of `migrations/0001_schema_baseline.sql` (+ the `alt_titles`
-- column added by 0002) for the default backend. SQLite has no schemas, so the
-- `suwayomi.` prefix is dropped; the dialect planner strips it from queries.
--
-- Type mapping:
--   INTEGER/BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY -> INTEGER PRIMARY KEY
--   BIGINT / INTEGER                                            -> INTEGER
--   BOOLEAN                                                     -> INTEGER (0/1)
--   VARCHAR(n) / TEXT                                           -> TEXT
--   DOUBLE PRECISION                                            -> REAL
--
-- Constraints PostgreSQL added with `ALTER TABLE … ADD CONSTRAINT` are inlined
-- here (SQLite cannot add them after the fact): foreign keys in the CREATE
-- TABLE body, UNIQUE as CREATE UNIQUE INDEX.
--
-- `page.index` and `meta.value` are quoted everywhere they appear — both are
-- reserved words in SQLite (`value` is accepted unquoted, but quoting keeps the
-- DDL and the queries uniform).
-- =====================================================================

CREATE TABLE IF NOT EXISTS extension (
    id              INTEGER PRIMARY KEY,
    apk_name        TEXT,
    store_index_url TEXT,
    icon_url        TEXT NOT NULL DEFAULT 'https://raw.githubusercontent.com/tachiyomiorg/tachiyomi/64ba127e7d43b1d7e6d58a6f5c9b2bd5fe0543f7/app/src/main/res/mipmap-xxxhdpi/ic_local_source.webp',
    name            TEXT NOT NULL,
    pkg_name        TEXT NOT NULL,
    apk_url         TEXT,
    jar_url         TEXT,
    extension_lib   TEXT,
    version_name    TEXT NOT NULL,
    version_code    INTEGER NOT NULL,
    lang            TEXT NOT NULL,
    content_warning INTEGER NOT NULL,
    is_installed    INTEGER NOT NULL DEFAULT 0,
    has_update      INTEGER NOT NULL DEFAULT 0,
    is_obsolete     INTEGER NOT NULL DEFAULT 0,
    class_name      TEXT NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_extension_pkg_name ON extension (pkg_name);
CREATE INDEX IF NOT EXISTS idx_extension_store_index_url ON extension (store_index_url);

CREATE TABLE IF NOT EXISTS source (
    id              INTEGER PRIMARY KEY,
    name            TEXT NOT NULL,
    lang            TEXT NOT NULL,
    extension       INTEGER NOT NULL,
    content_warning INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (extension) REFERENCES extension (id)
);

CREATE INDEX IF NOT EXISTS idx_source_extension ON source (extension);

CREATE TABLE IF NOT EXISTS manga (
    id                          INTEGER PRIMARY KEY,
    url                         TEXT NOT NULL,
    title                       TEXT NOT NULL,
    initialized                 INTEGER NOT NULL DEFAULT 0,
    artist                      TEXT,
    author                      TEXT,
    description                 TEXT,
    genre                       TEXT,
    alt_titles                  TEXT NOT NULL DEFAULT '[]',
    status                      INTEGER NOT NULL DEFAULT 0,
    thumbnail_url               TEXT,
    thumbnail_url_last_fetched  INTEGER NOT NULL DEFAULT 0,
    in_library                  INTEGER NOT NULL DEFAULT 0,
    in_library_at               INTEGER NOT NULL DEFAULT 0,
    source                      INTEGER NOT NULL,
    real_url                    TEXT,
    last_fetched_at             INTEGER NOT NULL DEFAULT 0,
    chapters_last_fetched_at    INTEGER NOT NULL DEFAULT 0,
    update_strategy             TEXT NOT NULL DEFAULT 'ALWAYS_UPDATE',
    last_modified_at            INTEGER NOT NULL DEFAULT 0,
    version                     INTEGER NOT NULL DEFAULT 0,
    is_syncing                  INTEGER NOT NULL DEFAULT 0,
    memo                        TEXT NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS chapter (
    id               INTEGER PRIMARY KEY,
    url              TEXT NOT NULL,
    name             TEXT NOT NULL,
    date_upload      INTEGER NOT NULL DEFAULT 0,
    chapter_number   REAL NOT NULL DEFAULT -1,
    scanlator        TEXT,
    read             INTEGER NOT NULL DEFAULT 0,
    bookmark         INTEGER NOT NULL DEFAULT 0,
    last_page_read   INTEGER NOT NULL DEFAULT 0,
    last_read_at     INTEGER NOT NULL DEFAULT 0,
    fetched_at       INTEGER NOT NULL DEFAULT 0,
    source_order     INTEGER NOT NULL,
    real_url         TEXT,
    is_downloaded    INTEGER NOT NULL DEFAULT 0,
    page_count       INTEGER NOT NULL DEFAULT -1,
    manga            INTEGER NOT NULL,
    koreader_hash    TEXT,
    last_modified_at INTEGER NOT NULL DEFAULT 0,
    version          INTEGER NOT NULL DEFAULT 0,
    is_syncing       INTEGER NOT NULL DEFAULT 0,
    memo             TEXT NOT NULL DEFAULT '{}',
    FOREIGN KEY (manga) REFERENCES manga (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_chapter ON chapter (url, manga);
CREATE INDEX IF NOT EXISTS idx_chapter_manga ON chapter (manga);

CREATE TABLE IF NOT EXISTS page (
    id        INTEGER PRIMARY KEY,
    "index"   INTEGER NOT NULL,
    url       TEXT NOT NULL,
    image_url TEXT,
    chapter   INTEGER NOT NULL,
    FOREIGN KEY (chapter) REFERENCES chapter (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_page_chapter ON page (chapter);

CREATE TABLE IF NOT EXISTS category (
    id                  INTEGER PRIMARY KEY,
    name                TEXT NOT NULL,
    sort_order          INTEGER NOT NULL DEFAULT 0,
    is_default          INTEGER NOT NULL DEFAULT 0,
    include_in_update   INTEGER NOT NULL DEFAULT -1,
    include_in_download INTEGER NOT NULL DEFAULT -1,
    version             INTEGER NOT NULL DEFAULT 0,
    uid                 INTEGER NOT NULL DEFAULT 0,
    last_modified_at    INTEGER NOT NULL DEFAULT 0,
    is_syncing          INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS category_manga (
    id       INTEGER PRIMARY KEY,
    category INTEGER NOT NULL,
    manga    INTEGER NOT NULL,
    FOREIGN KEY (category) REFERENCES category (id) ON DELETE CASCADE,
    FOREIGN KEY (manga) REFERENCES manga (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_category_manga ON category_manga (manga, category);
CREATE INDEX IF NOT EXISTS idx_category_manga_category ON category_manga (category);
CREATE INDEX IF NOT EXISTS idx_category_manga_manga ON category_manga (manga);

CREATE TABLE IF NOT EXISTS category_meta (
    id           INTEGER PRIMARY KEY,
    meta_key     TEXT NOT NULL,
    "value"      TEXT NOT NULL,
    category_ref INTEGER NOT NULL,
    FOREIGN KEY (category_ref) REFERENCES category (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_category_meta ON category_meta (category_ref, meta_key);
CREATE INDEX IF NOT EXISTS idx_category_meta_category ON category_meta (category_ref);

CREATE TABLE IF NOT EXISTS chapter_meta (
    id          INTEGER PRIMARY KEY,
    meta_key    TEXT NOT NULL,
    "value"     TEXT NOT NULL,
    chapter_ref INTEGER NOT NULL,
    FOREIGN KEY (chapter_ref) REFERENCES chapter (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_chapter_meta ON chapter_meta (chapter_ref, meta_key);
CREATE INDEX IF NOT EXISTS idx_chapter_meta_chapter ON chapter_meta (chapter_ref);

CREATE TABLE IF NOT EXISTS manga_meta (
    id        INTEGER PRIMARY KEY,
    meta_key  TEXT NOT NULL,
    "value"   TEXT NOT NULL,
    manga_ref INTEGER NOT NULL,
    FOREIGN KEY (manga_ref) REFERENCES manga (id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_manga_meta ON manga_meta (manga_ref, meta_key);
CREATE INDEX IF NOT EXISTS idx_manga_meta_manga ON manga_meta (manga_ref);

CREATE TABLE IF NOT EXISTS source_meta (
    id         INTEGER PRIMARY KEY,
    meta_key   TEXT NOT NULL,
    "value"    TEXT NOT NULL,
    source_ref INTEGER NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_source_meta ON source_meta (source_ref, meta_key);
CREATE INDEX IF NOT EXISTS idx_source_meta_source ON source_meta (source_ref);

-- No FK: the seed row has id = 0 and the table is written before `manga_meta`
-- rows exist for a fresh install.
CREATE TABLE IF NOT EXISTS global_meta (
    id       INTEGER PRIMARY KEY,
    meta_key TEXT NOT NULL,
    "value"  TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_global_meta ON global_meta (meta_key);

CREATE TABLE IF NOT EXISTS extension_store (
    id                 INTEGER PRIMARY KEY,
    index_url          TEXT NOT NULL,
    name               TEXT NOT NULL,
    badge_label        TEXT NOT NULL,
    signing_key        TEXT NOT NULL,
    contact_website    TEXT NOT NULL,
    contact_discord    TEXT,
    is_legacy          INTEGER NOT NULL DEFAULT 0,
    extension_list_url TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_extension_store_index_url ON extension_store (index_url);

CREATE TABLE IF NOT EXISTS track_record (
    id                INTEGER PRIMARY KEY,
    manga_id          INTEGER NOT NULL,
    sync_id           INTEGER NOT NULL,
    remote_id         INTEGER NOT NULL,
    library_id        INTEGER,
    title             TEXT NOT NULL,
    last_chapter_read REAL NOT NULL,
    total_chapters    INTEGER NOT NULL,
    status            INTEGER NOT NULL,
    score             REAL NOT NULL,
    remote_url        TEXT NOT NULL,
    start_date        INTEGER NOT NULL,
    finish_date       INTEGER NOT NULL,
    private           INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (manga_id) REFERENCES manga (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_track_record_manga ON track_record (manga_id);

CREATE TABLE IF NOT EXISTS track_search (
    id                    INTEGER PRIMARY KEY,
    tracker_id            INTEGER NOT NULL,
    remote_id             INTEGER NOT NULL,
    title                 TEXT NOT NULL,
    total_chapters        INTEGER NOT NULL,
    tracking_url          TEXT NOT NULL,
    cover_url             TEXT NOT NULL,
    summary               TEXT NOT NULL,
    publishing_status     TEXT NOT NULL,
    publishing_type       TEXT NOT NULL,
    start_date            TEXT NOT NULL,
    library_id            INTEGER DEFAULT NULL,
    last_chapter_read     REAL NOT NULL DEFAULT 0,
    status                INTEGER NOT NULL DEFAULT 0,
    score                 REAL NOT NULL DEFAULT 0,
    started_reading_date  INTEGER NOT NULL DEFAULT 0,
    finished_reading_date INTEGER NOT NULL DEFAULT 0,
    private               INTEGER NOT NULL DEFAULT 0,
    authors               TEXT DEFAULT NULL,
    artists               TEXT DEFAULT NULL
);
